name: Build and Push Docker Image with Unique Tag

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  workflow_dispatch:

env:
  IMAGE_NAME: entto-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set unique image tag
        id: set-tag
        run: echo "::set-output name=tag::$(git rev-parse --short $GITHUB_SHA)"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Set image name
      #   id: set-image-name
      #   run: echo "::set-output name=image-name::${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }}"

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }}

      - name: Cleanup
        run: docker logout

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          # kubernetes 설정정보 저장소
          repository: SangYunLeee/argocd-enttolog
          ref: main
          # 다른 저장소에 push 하려면 Personal Access Token이 필요.
          token: ${{ secrets.ACTION_TOKEN }}
          path: argocd-enttolog

      - name: Update Kubernetes Image Tag
        uses: mikefarah/yq@master
        with:
          cmd: |
            cd argocd-enttolog/applications/entto/manifests
            yq -i '.backend.image.tag = "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }}"' 'values.yaml'
      # 새 이미지 버전으로 파일 수정
      - name: Update Kubernetes resources
        run: |
          cd argocd-enttolog/applications/entto/manifests
          kustomize edit set image
          cat kustomization.yaml

      # 수정된 파일 commit & push
      - name: Commit files
        run: |
          cd argocd-enttolog
          git config --global user.email "sororiri@gmail.com"
          git config --global user.name "lee sangyun"
          git commit -am "Update image tag"
          git push -u origin main
